name: note
description: A full-platform video note-taking software. Watch the video and take notes at the same time. Of course it's more than that.

publish_to: 'none'

version: 0.0.4

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #ui库
  getwidget: 4.0.0

  velocity_x: ^4.1.2
  #视频组件
  media_kit: 1.1.10                             # Primary package.
  media_kit_video: 1.2.4                        # For video rendering.
  media_kit_libs_video: 1.0.4                   # Native video dependencies.
  #markdown组件
  flutter_markdown: ^0.6.17+2
  #富文本编辑器组件
  flutter_quill: ^9.3.10
  flutter_quill_extensions: ^9.3.10
  #路由组件
  get: ^4.6.6
  #持久化组件
  # shared_preferences: ^2.2.1
  #路径组件
  path_provider: ^2.1.1
  #安卓路径
  external_path: ^1.0.3
  #文件选择
  path: ^1.8.3
  file_picker:
    path: ./plugins/flutter_file_picker

  #权限组件
  permission_handler: ^11.0.0
  #吐司弹窗框架
  flutter_smart_dialog: ^4.9.5+1
  #分享
#  share_plus: ^9.0.0
  #设备信息
  #  device_info_plus: ^9.0.3
  package_info_plus: ^4.2.0
  #日志
  logger: ^2.0.1
  #打开url
#  url_launcher: ^6.1.12
  #崩溃信息
  #  sentry_flutter: ^7.9.0
  #悬浮按钮
  flutter_speed_dial: ^7.0.0
  #pdf
#  pdf: ^3.10.4
  #白板工具
  flutter_drawing_board: ^0.5.0
  #  手写签名
#  syncfusion_flutter_signaturepad: ^23.1.43
  # 图片扩展
#  extended_image: 8.0.2
  # 图片裁剪
#  crop_image: ^1.0.11
  #录音
#  record: ^5.0.1
  #插件系统
#  flutter_js: ^0.8.0
  #拖拽控件
  multi_split_view: ^2.4.0
  #悬浮组件,将视频窗口悬浮
  floating_overlay: ^1.2.1
  #搜索框组件
  super_cupertino_navigation_bar: ^1.1.2

  #屏幕工具响应式布局
  flutter_screenutil: ^5.9.0
  #开屏动画
#  flutter_native_splash: ^2.3.5

  #pdf编辑
  #  pdftron_flutter: ^1.0.1-22
  #代码编辑
#  flutter_code_editor: ^0.3.1
  #工具类 包含shared_preferences
  nb_utils: ^7.0.2
  #网格视图布局组件
  flutter_staggered_grid_view: ^0.7.0
  #上拉下拉刷新
#  pull_to_refresh: ^2.0.0
  #底部导航栏
  #  persistent_bottom_nav_bar: ^5.0.2
  #响应式UI
  responsive_framework: ^1.1.1
  #  #高级屏幕截图
  #  screenshot: ^2.1.0
  #键盘行为
#  keyboard_actions: ^4.2.0
  #  设置UI
#  settings_ui: ^2.0.2
  #服务器组件
  shelf: ^1.4.1
  #websocket 跨端通信
  web_socket_channel: ^2.4.0
#  socket_io_client: ^2.0.3+1
  #  版本更新
#  upgrader: ^8.2.0
  #  序列化
#  freezed_annotation: ^2.4.1
#  json_annotation: ^4.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  #  代码规范
  flutter_lints: ^2.0.3
  #生成器
  build_runner: ^2.4.6
  #应用图标
  flutter_launcher_icons: ^0.13.1
  # 序列化
#  freezed: ^2.4.5
#  json_serializable: ^6.7.1
  #isar代码生成工具
#  isar_generator: *isar_version



#应用图标
flutter_launcher_icons:
  image_path: "assets/icons/ml.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/ml.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/ml.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/ml.png"
#开屏图
#flutter_native_splash:
#  color: "#42a5f5"
#  #background_image: "assets/background.png"
#  android_12:
#  #color: "#42a5f5"
#  #image: assets/android12splash.png


flutter:
  uses-material-design: true
  assets:
    - assets/images/ml.png
flutter_intl:
  enabled: true

